"""Command-line entry point for Sentinel V3 baseline training."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

import pandas as pd

from sentinel.ml.data import MLError, load_dataset
from sentinel.ml.models import DEFAULT_RANDOM_STATE
from sentinel.ml.reporting import print_model_report, print_split_report
from sentinel.ml.splitting import chronological_split
from sentinel.ml.training import save_artifacts, train_baselines


def default_output_dir(feature_csv: str | Path) -> Path:
    """Return artifacts/<dataset-name> for a V2 feature CSV."""
    stem = Path(feature_csv).stem.removesuffix("_features")
    return Path("artifacts") / stem


def _non_negative_integer(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("must be non-negative")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Train and evaluate leakage-safe Sentinel V3 baselines on a V2 CSV."
        )
    )
    parser.add_argument("feature_csv", type=Path, help="CSV generated by sentinel-features")
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Artifact directory (default: artifacts/<dataset-name>)",
    )
    parser.add_argument(
        "--random-state",
        type=_non_negative_integer,
        default=DEFAULT_RANDOM_STATE,
        help=f"Deterministic model seed (default: {DEFAULT_RANDOM_STATE})",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    output_dir = args.output_dir or default_output_dir(args.feature_csv)

    try:
        print(f"Loading and validating {args.feature_csv}...")
        data = load_dataset(args.feature_csv)
        print(f"Validated {len(data):,} snapshots with 8 historical predictors.")
        splits = chronological_split(data)
        result = train_baselines(
            splits,
            random_state=args.random_state,
            progress=print,
        )
        print_split_report(splits)
        print_model_report(result)
        print(
            "\nLeakage audit: PASS (date-grouped chronological split; train-only "
            "preprocessing; validation-only selection; final-only test use; "
            "historical feature whitelist)."
        )
        model_path, metadata_path = save_artifacts(result, output_dir)
    except (
        MLError,
        OSError,
        UnicodeError,
        pd.errors.ParserError,
        ValueError,
    ) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print(f"\nModel artifact: {model_path}")
    print(f"Metadata artifact: {metadata_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
